## Google API Table Pivot

In [385]:
!which python

/home/eduardo/anaconda3/bin/python

In [386]:
!pip install oauthlib
!pip3 install gspread
!pip3 install --upgrade google-api-python-client oauth2client

Requirement already satisfied: oauthlib in /home/eduardo/anaconda3/lib/python3.8/site-packages (3.1.1)
Requirement already satisfied: gspread in /home/eduardo/anaconda3/lib/python3.8/site-packages (4.0.1)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /home/eduardo/.local/lib/python3.8/site-packages (from gspread) (0.4.6)
Requirement already satisfied: google-auth>=1.12.0 in /home/eduardo/.local/lib/python3.8/site-packages (from gspread) (1.30.1)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-auth>=1.12.0->gspread) (4.2.2)
Requirement already satisfied: setuptools>=40.3.0 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from google-auth>=1.12.0->gspread) (52.0.0.post20210125)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/eduardo/.local/lib/python3.8/site-packages (from google-auth>=1.12.0->gspread) (4.7.2)
Requirement already satisfied: six>=1.9.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-auth>=1.12.0->gspread) (1.15.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/eduardo/.local/lib/python3.8/site-packages (from google-auth>=1.12.0->gspread) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-auth-oauthlib>=0.4.1->gspread) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/eduardo/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.1.1)
Requirement already satisfied: requests>=2.0.0 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (1.26.4)
Requirement already satisfied: google-api-python-client in /home/eduardo/.local/lib/python3.8/site-packages (2.22.0)
Requirement already satisfied: oauth2client in /home/eduardo/anaconda3/lib/python3.8/site-packages (4.1.3)
Requirement already satisfied: google-auth<3.0.0dev,>=1.16.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-api-python-client) (1.30.1)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-api-python-client) (3.0.1)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-api-python-client) (0.19.1)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-api-python-client) (0.1.0)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.21.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-api-python-client) (2.0.1)
Requirement already satisfied: rsa>=3.1.4 in /home/eduardo/.local/lib/python3.8/site-packages (from oauth2client) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /home/eduardo/.local/lib/python3.8/site-packages (from oauth2client) (0.2.8)
Requirement already satisfied: six>=1.6.1 in /home/eduardo/.local/lib/python3.8/site-packages (from oauth2client) (1.15.0)
Requirement already satisfied: pyasn1>=0.1.7 in /home/eduardo/.local/lib/python3.8/site-packages (from oauth2client) (0.4.8)
Requirement already satisfied: setuptools>=40.3.0 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (52.0.0.post20210125)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (1.53.0)
Requirement already satisfied: protobuf>=3.12.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (3.17.2)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2.25.1)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/eduardo/.local/lib/python3.8/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (4.2.2)
Requirement already satisfied: pyparsing<3,>=2.4.2 in /home/eduardo/.local/lib/python3.8/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client) (2.4.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/eduardo/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2020.12.5)

In [582]:
from __future__ import print_function
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials

import pandas as pd
from oauth2client.service_account import ServiceAccountCredentials

import time
import ipywidgets as widgets

import json

In [560]:
# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']

# The ID and range of a sample spreadsheet.
SAMPLE_SPREADSHEET_ID = '1DRD97TAw2WIuTCG0Nh6BW-aVvDKAgY1wvJb38V-3vU8'
SAMPLE_RANGE_NAME = 'Reto1!A2:E'

TEST_SPREADSHEET_ID='1aqM5_3d8Wrw522LF5scS2h28hCvNSF8FO2C8nOe4Ypc'

index_columns=['Author','Sentiment', 'Country','Theme']

In [561]:
# Use main to use datasheet in owner drive
def main():
    """Shows basic usage of the Sheets API.
    Prints values from a sample spreadsheet.
    """
    creds = None
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'client_secret_264260318778-6q86htiapp1m19qc88ksmddpfnfdjkvi.apps.googleusercontent.com.json', SCOPES)
            creds = flow.run_local_server(port=8080)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            token.write(creds.to_json())

    service = build('sheets', 'v4', credentials=creds)

    # Call the Sheets API
    sheet = service.spreadsheets()
    result = sheet.values().get(spreadsheetId=SAMPLE_SPREADSHEET_ID,
                                range=SAMPLE_RANGE_NAME).execute()
    values = result.get('values', [])

# Use main_test to use datasheet in tester drive
def main_test():
    """Shows basic usage of the Sheets API.
    Prints values from a sample spreadsheet.
    """
    creds = None
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'client_secret_264260318778-6q86htiapp1m19qc88ksmddpfnfdjkvi.apps.googleusercontent.com.json', SCOPES)
            creds = flow.run_local_server(port=8080)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            token.write(creds.to_json())

    service = build('sheets', 'v4', credentials=creds)

    # Call the Sheets API
    sheet = service.spreadsheets()
    result = sheet.values().get(spreadsheetId=TEST_SPREADSHEET_ID,
                                range=SAMPLE_RANGE_NAME).execute()
    values = result.get('values', [])

    #if not values:
    #    print('No data found.')
    #else:
    #    print('Author, Sentiment, Country, Theme:')
    #    for row in values:
            # Print columns A and E, which correspond to indices 0 and 4.
    #        print(f'{row[0]}, {row[1]}, {row[2]}, {row[3]}')
    return values

In [562]:
table_values = main_test()
#table_values = main()

In [928]:
df = pd.DataFrame(table_values, columns=index_columns)
df
df_c = pd.DataFrame(table_values, columns=index_columns)
df_t = pd.DataFrame(table_values, columns=index_columns)

In [877]:
pivot1 = df.pivot_table(index=['Author','Sentiment'], columns=['Country'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
pivot2 = df.pivot_table(index=['Author','Sentiment'], columns=['Theme'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
all_data = pd.merge(pivot1, pivot2, 'left', on = ['Author','Sentiment'] )
all_data

                      Theme                                                \
Country             Bolivia  Chile Colombia Ecuador Francia Panama   Peru
Author    Sentiment
Joseluna  Positive    FALSE  FALSE    FALSE    TRUE   FALSE  FALSE   TRUE
alberto   Positive    FALSE  FALSE    FALSE   FALSE    TRUE  FALSE  FALSE
carlosz   Negative    FALSE  FALSE    FALSE   FALSE   FALSE  FALSE  FALSE
jgbesq    Negative    FALSE  FALSE    FALSE   FALSE   FALSE   TRUE  FALSE
nico23    Neutral     FALSE  FALSE    FALSE   FALSE   FALSE  FALSE  FALSE
nuri90    Neutral     FALSE  FALSE    FALSE   FALSE   FALSE  FALSE  FALSE
santiago8 Neutral      TRUE   TRUE    FALSE   FALSE   FALSE  FALSE  FALSE
sixt93    Negative    FALSE  FALSE     TRUE   FALSE   FALSE  FALSE  FALSE

                                                  Country                \
Country             Portugal  Spain     UK    USA      CA     EV     KS
Author    Sentiment
Joseluna  Positive     FALSE  FALSE  FALSE  FALSE   FALSE  FALSE   TRUE
alberto   Positive     FALSE  FALSE  FALSE   TRUE   FALSE  FALSE   TRUE
carlosz   Negative     FALSE  FALSE  FALSE   TRUE   FALSE  FALSE  FALSE
jgbesq    Negative     FALSE  FALSE   TRUE  FALSE   FALSE  FALSE   TRUE
nico23    Neutral      FALSE  FALSE  FALSE   TRUE   FALSE  FALSE  FALSE
nuri90    Neutral      FALSE   TRUE  FALSE  FALSE   FALSE   TRUE  FALSE
santiago8 Neutral      FALSE  FALSE  FALSE  FALSE   FALSE  FALSE   TRUE
sixt93    Negative      TRUE  FALSE  FALSE  FALSE    TRUE  FALSE  FALSE


Country                 OT     PA
Author    Sentiment
Joseluna  Positive   FALSE   TRUE
alberto   Positive    TRUE  FALSE
carlosz   Negative    TRUE  FALSE
jgbesq    Negative   FALSE   TRUE
nico23    Neutral    FALSE   TRUE
nuri90    Neutral    FALSE  FALSE
santiago8 Neutral    FALSE   TRUE
sixt93    Negative    TRUE  FALSE

In [620]:
out = widgets.HTML()
display(out)
while True:
    time.sleep(1)
    table_values = main_test()
    df = pd.DataFrame(table_values, columns=index_columns)
    pivot1 = df.pivot_table(index=['Author','Sentiment'], columns=['Country'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
    pivot2 = df.pivot_table(index=['Author','Sentiment'], columns=['Theme'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
    all_data = pd.merge(pivot1, pivot2, 'left', on = ['Author','Sentiment'] )
    
    out.value = all_data.to_html().replace("\n",'\\').replace("\\",'')

HTML(value='')

KeyboardInterrupt:

In [549]:
import pickle

In [985]:
#change this by your sheet ID
SAMPLE_SPREADSHEET_ID_input = TEST_SPREADSHEET_ID
SCOPES_2 = ['https://www.googleapis.com/auth/spreadsheets']
SAMPLE_RANGE_NAME_w = 'ejemplo_reto1!A2:AA1000'

def Create_Service(client_secret_file, api_service_name, api_version, *scopes):
    global service
    SCOPES = [scope for scope in scopes[0]]
    #print(SCOPES)
    
    cred = None

    if os.path.exists('token_write.pickle'):
        with open('token_write.pickle', 'rb') as token:
            cred = pickle.load(token)

    if not cred or not cred.valid:
        if cred and cred.expired and cred.refresh_token:
            cred.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(client_secret_file, SCOPES)
            cred = flow.run_local_server()

        with open('token_write.pickle', 'wb') as token:
            pickle.dump(cred, token)

    try:
        service = build(api_service_name, api_version, credentials=cred)
        print(api_service_name, 'service created successfully')
        #return service
    except Exception as e:
        print(e)
        #return None

In [986]:
# change 'my_json_file.json' by your downloaded JSON file.
Create_Service('client_secret_264260318778-6q86htiapp1m19qc88ksmddpfnfdjkvi.apps.googleusercontent.com.json', 'sheets', 'v4',['https://www.googleapis.com/auth/spreadsheets'])

sheets service created successfully

In [568]:
def Export_Data_To_Sheets():
    response_date = service.spreadsheets().values().update(
        spreadsheetId=SAMPLE_SPREADSHEET_ID_input,
        valueInputOption='RAW',
        range=SAMPLE_RANGE_NAME_w,
        body=dict(
            majorDimension='ROWS',
            values=all_data.reset_index().T.values.tolist())
    ).execute()
    print('Sheet successfully Updated')

In [501]:
Export_Data_To_Sheets()

Sheet successfully Updated

In [621]:
values_t=all_data
print(values_t.values.tolist())

[['FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE'], ['FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE'], ['FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE'], ['FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE'], ['FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE'], ['FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE'], ['TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE'], ['FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE']]

In [994]:
out = widgets.HTML()
display(out)
while True:
    time.sleep(2)
    table_values = main_test()
    
    df = pd.DataFrame(table_values, columns=index_columns)
    df_c = pd.DataFrame(table_values, columns=index_columns)
    df_t = pd.DataFrame(table_values, columns=index_columns)

    df_t.pop('Country')
    df_c.pop('Theme')

    pivot_test_c = df_c.pivot_table(index=['Author','Sentiment'], columns=['Country'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE').reset_index()


    pivot_test_t = df_t.pivot_table(index=['Author','Sentiment'], columns=['Theme'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE').reset_index()

    pivot_test_all_data = pd.merge(pivot_test_c, pivot_test_t, 'left', on = ['Author','Sentiment'] )
    

    #df = pd.DataFrame(table_values, columns=index_columns)
    #pivot1 = df.pivot_table(index=['Author','Sentiment'], columns=['Country'], values=['Sentiment'],
    #                    aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
    #pivot2 = df.pivot_table(index=['Author','Sentiment'], columns=['Theme'], values=['Sentiment'],
    #                    aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
    #all_data = pd.merge(pivot1, pivot2, 'left', on = ['Author','Sentiment'] )
    
    out.value = pivot_test_all_data.to_html().replace("\n",'\\').replace("\\",'')
    #all_data_f=all_data
    
    

    #
  
    #


    response_date = service.spreadsheets().values().update(
        spreadsheetId=SAMPLE_SPREADSHEET_ID_input,
        valueInputOption='RAW',
        range=SAMPLE_RANGE_NAME_w,
        body=dict(
            majorDimension='ROWS',
            values=pivot_test_all_data.T.reset_index().T.values.tolist())
    ).execute()
    print('Sheet successfully Updated')

HTML(value='')

Sheet successfully Updated
Sheet successfully Updated
Sheet successfully Updated
Sheet successfully Updated
Sheet successfully Updated
Sheet successfully Updated
Sheet successfully Updated
Sheet successfully Updated
Sheet successfully Updated
Sheet successfully Updated
Sheet successfully Updated

KeyboardInterrupt:

In [639]:

j = to_json_multiindex(all_data)
d = read_json_multiindex(j)

In [787]:
df

       Author Sentiment   Country Theme
0    Joseluna  Positive   Ecuador    PA
1      sixt93  Negative  Colombia    CA
2     alberto  Positive   Francia    OT
3     carlosz  Negative       USA    OT
4      jgbesq  Negative        UK    PA
5      nuri90   Neutral     Spain    EV
6   santiago8   Neutral     Chile    KS
7    Joseluna  Positive      Peru    KS
8     alberto  Positive   Francia    OT
9      jgbesq  Negative    Panama    KS
10     sixt93  Negative  Portugal    OT
11  santiago8   Neutral     Chile    KS
12  santiago8   Neutral   Bolivia    PA
13     nico23   Neutral       USA    PA
14    alberto  Positive       USA    KS

In [788]:
pt1= df.pivot_table(index=['Author','Sentiment'], columns='Country',aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
pt1

                      Theme                                                \
Country             Bolivia  Chile Colombia Ecuador Francia Panama   Peru
Author    Sentiment
Joseluna  Positive    FALSE  FALSE    FALSE    TRUE   FALSE  FALSE   TRUE
alberto   Positive    FALSE  FALSE    FALSE   FALSE    TRUE  FALSE  FALSE
carlosz   Negative    FALSE  FALSE    FALSE   FALSE   FALSE  FALSE  FALSE
jgbesq    Negative    FALSE  FALSE    FALSE   FALSE   FALSE   TRUE  FALSE
nico23    Neutral     FALSE  FALSE    FALSE   FALSE   FALSE  FALSE  FALSE
nuri90    Neutral     FALSE  FALSE    FALSE   FALSE   FALSE  FALSE  FALSE
santiago8 Neutral      TRUE   TRUE    FALSE   FALSE   FALSE  FALSE  FALSE
sixt93    Negative    FALSE  FALSE     TRUE   FALSE   FALSE  FALSE  FALSE


Country             Portugal  Spain     UK    USA
Author    Sentiment
Joseluna  Positive     FALSE  FALSE  FALSE  FALSE
alberto   Positive     FALSE  FALSE  FALSE   TRUE
carlosz   Negative     FALSE  FALSE  FALSE   TRUE
jgbesq    Negative     FALSE  FALSE   TRUE  FALSE
nico23    Neutral      FALSE  FALSE  FALSE   TRUE
nuri90    Neutral      FALSE   TRUE  FALSE  FALSE
santiago8 Neutral      FALSE  FALSE  FALSE  FALSE
sixt93    Negative      TRUE  FALSE  FALSE  FALSE

In [756]:
df1 = df

In [757]:
tuples = list(zip(*[df1['Author'],df1['Sentiment']]))
tuples

[('Joseluna', 'Positive'),
 ('sixt93', 'Negative'),
 ('alberto', 'Positive'),
 ('carlosz', 'Negative'),
 ('jgbesq', 'Negative'),
 ('nuri90', 'Neutral'),
 ('santiago8', 'Neutral'),
 ('Joseluna', 'Positive'),
 ('alberto', 'Positive'),
 ('jgbesq', 'Negative'),
 ('sixt93', 'Negative'),
 ('santiago8', 'Neutral'),
 ('santiago8', 'Neutral'),
 ('nico23', 'Neutral'),
 ('alberto', 'Positive')]

In [758]:
index = pd.MultiIndex.from_tuples(tuples, names=['Author', 'Sentiment'])
index

MultiIndex([( 'Joseluna', 'Positive'),
            (   'sixt93', 'Negative'),
            (  'alberto', 'Positive'),
            (  'carlosz', 'Negative'),
            (   'jgbesq', 'Negative'),
            (   'nuri90',  'Neutral'),
            ('santiago8',  'Neutral'),
            ( 'Joseluna', 'Positive'),
            (  'alberto', 'Positive'),
            (   'jgbesq', 'Negative'),
            (   'sixt93', 'Negative'),
            ('santiago8',  'Neutral'),
            ('santiago8',  'Neutral'),
            (   'nico23',  'Neutral'),
            (  'alberto', 'Positive')],
           names=['Author', 'Sentiment'])

In [762]:
s= df.pivot_table(index=index, columns=['Country'],values=['Sentiment'],aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
#s.values.tolist()
s.columns
s.index
s.to_records().tolist()

[(('Joseluna', 'Positive'),
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE'),
 (('alberto', 'Positive'),
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE'),
 (('carlosz', 'Negative'),
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE'),
 (('jgbesq', 'Negative'),
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE'),
 (('nico23', 'Neutral'),
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE'),
 (('nuri90', 'Neutral'),
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE'),
 (('santiago8', 'Neutral'),
  'TRUE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE'),
 (('sixt93', 'Negative'),
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE')]

In [896]:
pvt1 = df.pivot_table(index=['Author','Sentiment'], columns=['Country'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
pvt2 = df.pivot_table(index=['Author','Sentiment'], columns=['Theme'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')
pv_all_data = pd.merge(pivot1, pivot2, 'left', on = ['Author','Sentiment'] )
l1 = pv_all_data.columns.tolist()

In [965]:
df_t

       Author Sentiment Theme
0    Joseluna  Positive    PA
1      sixt93  Negative    CA
2     alberto  Positive    OT
3     carlosz  Negative    OT
4      jgbesq  Negative    PA
5      nuri90   Neutral    EV
6   santiago8   Neutral    KS
7    Joseluna  Positive    KS
8     alberto  Positive    OT
9      jgbesq  Negative    KS
10     sixt93  Negative    OT
11  santiago8   Neutral    KS
12  santiago8   Neutral    PA
13     nico23   Neutral    PA
14    alberto  Positive    KS

In [935]:
df_t.pop('Country')
df_c.pop('Theme')

0     PA
1     CA
2     OT
3     OT
4     PA
5     EV
6     KS
7     KS
8     OT
9     KS
10    OT
11    KS
12    PA
13    PA
14    KS
Name: Theme, dtype: object

In [937]:
df_c

       Author Sentiment   Country
0    Joseluna  Positive   Ecuador
1      sixt93  Negative  Colombia
2     alberto  Positive   Francia
3     carlosz  Negative       USA
4      jgbesq  Negative        UK
5      nuri90   Neutral     Spain
6   santiago8   Neutral     Chile
7    Joseluna  Positive      Peru
8     alberto  Positive   Francia
9      jgbesq  Negative    Panama
10     sixt93  Negative  Portugal
11  santiago8   Neutral     Chile
12  santiago8   Neutral   Bolivia
13     nico23   Neutral       USA
14    alberto  Positive       USA

       Author Sentiment   Country
0    Joseluna  Positive   Ecuador
1      sixt93  Negative  Colombia
2     alberto  Positive   Francia
3     carlosz  Negative       USA
4      jgbesq  Negative        UK
5      nuri90   Neutral     Spain
6   santiago8   Neutral     Chile
7    Joseluna  Positive      Peru
8     alberto  Positive   Francia
9      jgbesq  Negative    Panama
10     sixt93  Negative  Portugal
11  santiago8   Neutral     Chile
12  santiago8   Neutral   Bolivia
13     nico23   Neutral       USA
14    alberto  Positive       USA

In [991]:
pivot_test_c = df_c.pivot_table(index=['Author','Sentiment'], columns=['Country'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE').reset_index()


pivot_test_t = df_t.pivot_table(index=['Author','Sentiment'], columns=['Theme'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE').reset_index()

pivot_test_all_data = pd.merge(pivot_test_c, pivot_test_t, 'left', on = ['Author','Sentiment'] )
pivot_test_all_data

,Author,Sentiment,Bolivia,Chile,Colombia,Ecuador,Francia,Panama,Peru,Portugal,Spain,UK,USA,CA,EV,KS,OT,PA
0,Joseluna,Positive,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE
1,alberto,Positive,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE
2,carlosz,Negative,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE
3,jgbesq,Negative,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE
4,nico23,Neutral,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE
5,nuri90,Neutral,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE
6,santiago8,Neutral,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE
7,sixt93,Negative,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE

In [993]:
pivot_test_all_data.T.reset_index().T.values.tolist()

[['Author',
  'Sentiment',
  'Bolivia',
  'Chile',
  'Colombia',
  'Ecuador',
  'Francia',
  'Panama',
  'Peru',
  'Portugal',
  'Spain',
  'UK',
  'USA',
  'CA',
  'EV',
  'KS',
  'OT',
  'PA'],
 ['Joseluna',
  'Positive',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'TRUE'],
 ['alberto',
  'Positive',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'TRUE',
  'TRUE',
  'FALSE'],
 ['carlosz',
  'Negative',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE'],
 ['jgbesq',
  'Negative',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'TRUE'],
 ['nico23',
  'Neutral',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE'],
 ['nuri90',
  'Neutral',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE'],
 ['santiago8',
  'Neutral',
  'TRUE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'TRUE'],
 ['sixt93',
  'Negative',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE']]

In [983]:
pivot_test_all_data.T.to_records().T.tolist()

[('Author',
  'Joseluna',
  'alberto',
  'carlosz',
  'jgbesq',
  'nico23',
  'nuri90',
  'santiago8',
  'sixt93'),
 ('Sentiment',
  'Positive',
  'Positive',
  'Negative',
  'Negative',
  'Neutral',
  'Neutral',
  'Neutral',
  'Negative'),
 ('Bolivia',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE'),
 ('Chile',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE'),
 ('Colombia',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE'),
 ('Ecuador',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE'),
 ('Francia',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE'),
 ('Panama',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE'),
 ('Peru',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE'),
 ('Portugal',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE'),
 ('Spain',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE'),
 ('UK', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE'),
 ('USA', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE'),
 ('CA', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE'),
 ('EV', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE'),
 ('KS', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE'),
 ('OT', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE'),
 ('PA', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE')]

In [971]:
pvt1 = df

pivot_test = pvt1.pivot_table(index=['Author','Sentiment'], columns=['Country'], values=['Sentiment'],
                        aggfunc=lambda x: 'TRUE', fill_value = 'FALSE').reset_index()


pivot_test_2 = df.pivot_table(index=['Author','Sentiment'], columns=['Theme'], values=['Sentiment'],
                    aggfunc=lambda x: 'TRUE', fill_value = 'FALSE')

pivot_test_all_data = pd.merge(pivot_test, pivot_test_2, 'left', on = ['Author','Sentiment'] )



pivot_test_all_data.columns

MultiIndex([(   'Author',         ''),
            ('Sentiment',         ''),
            (    'Theme',  'Bolivia'),
            (    'Theme',    'Chile'),
            (    'Theme', 'Colombia'),
            (    'Theme',  'Ecuador'),
            (    'Theme',  'Francia'),
            (    'Theme',   'Panama'),
            (    'Theme',     'Peru'),
            (    'Theme', 'Portugal'),
            (    'Theme',    'Spain'),
            (    'Theme',       'UK'),
            (    'Theme',      'USA'),
            (  'Country',       'CA'),
            (  'Country',       'EV'),
            (  'Country',       'KS'),
            (  'Country',       'OT'),
            (  'Country',       'PA')],
           names=[None, 'Country'])

In [970]:
pivot_test.T.reset_index().T.values.tolist()

[['Author',
  'Sentiment',
  'Theme',
  'Theme',
  'Theme',
  'Theme',
  'Theme',
  'Theme',
  'Theme',
  'Theme',
  'Theme',
  'Theme',
  'Theme'],
 ['',
  '',
  'Bolivia',
  'Chile',
  'Colombia',
  'Ecuador',
  'Francia',
  'Panama',
  'Peru',
  'Portugal',
  'Spain',
  'UK',
  'USA'],
 ['Joseluna',
  'Positive',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE'],
 ['alberto',
  'Positive',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE'],
 ['carlosz',
  'Negative',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE'],
 ['jgbesq',
  'Negative',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE'],
 ['nico23',
  'Neutral',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE'],
 ['nuri90',
  'Neutral',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE'],
 ['santiago8',
  'Neutral',
  'TRUE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE'],
 ['sixt93',
  'Negative',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE',
  'FALSE',
  'TRUE',
  'FALSE',
  'FALSE',
  'FALSE']]